# Generated by Django 2.0 on 2018-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1better', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
