# Generated by Django 2.0 on 2018-01-12 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1better', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='f1better.Driver'),
        ),
    ]
