# Generated by Django 2.0.1 on 2018-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1better', '0002_auto_20180103_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='lol', max_length=250),
            preserve_default=False,
        ),
    ]
