# Generated by Django 2.0 on 2018-01-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1better', '0003_remove_race_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='f1better.Driver'),
        ),
    ]
