# Generated by Django 2.0 on 2018-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1better', '0004_auto_20180111_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.CharField(default='https://i.imgur.com/xrM0pYH.png', max_length=1000),
        ),
    ]
