# Generated by Django 2.0 on 2018-01-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1better', '0006_auto_20180111_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='finished',
            new_name='ended',
        ),
    ]
